### PR TITLE
Adding new typos that I've seen

### PR DESCRIPTION
**Pull request by benrugg**
Hi @charliepark - 

I'm just now adding fat_fingers to a project. I love the mentality behind what you created - just change the email address for the user behind the scenes.

I've seen hundreds of typos in my user's emails, and most of them were covered by your code. I updated it to add more new cases (expand the details on my commit to see them).

Thanks for making this. Let me know if you want me to change anything that I just submitted.

### CODE REVIEW

**Comment by benrugg** [comment]
Fixes #2 

@SergeyKishenin and @psugihara, I've also fixed ya.ru in this version.

**Comment by benrugg** [comment]
Hey @charliepark - I know what it's like to be way too busy to get back into a project that I made years ago. I've added Travis CI so you can see that the tests are all passing:

https://travis-ci.org/benrugg/fat_fingers

**Comment by benrugg** [comment]
Hi @charliepark - 

I'd love to be able to push my recent updates to the gem, and keep fat_fingers updated in the future. Is there any way you'd consider adding me as a collaborator on the repo and on rubygems?

**Comment by charliepark** [comment]
Hey there, Ben. Could you shoot me an email at charlie@charliepark.org? I'd be interested in transferring ownership of this repo over to you if you're interested in being the "official?" maintainer of it. I'm not really sure what's involved in that, but I'd love to get this in the hands of someone who'll be more responsible with it than I've been. Let me know?

**Pull request merged**
